import path from 'node:path';
import { ensureDir, writeFileIfMissing } from '../fs.js';
import {
  getDefaultCodeStyleRule,
  getDefaultCommand,
  getDefaultCommitPrepModuleReadme,
  getDefaultCommitPrepSkill,
  getDefaultConfigYaml,
  getDefaultPostmortemCaseTemplate,
  getDefaultPostmortemIndexTemplate,
  getDefaultPostmortemModuleReadme,
  getDefaultPostmortemModuleRules,
  getDefaultPostmortemModuleSkill,
  getDefaultPostmortemRetrospectiveTemplate,
  getDefaultProcessRule,
  getDefaultRalphLoopAssemblerPrompt,
  getDefaultRalphLoopAssemblyRubric,
  getDefaultRalphLoopDecomposeHeuristics,
  getDefaultRalphLoopEvaluatorPrompt,
  getDefaultRalphLoopGeneratorPrompt,
  getDefaultRalphLoopHostProfiles,
  getDefaultRalphLoopIterationLogSchema,
  getDefaultRalphLoopModuleReadme,
  getDefaultRalphLoopOnePagerRubric,
  getDefaultRalphLoopRunDirReadmeTemplate,
  getDefaultRalphLoopRubricsReadme,
  getDefaultRalphLoopSkill,
  getDefaultRalphLoopTaskSpecTemplate,
  getDefaultReadme,
  getDefaultRule,
  getDefaultSkill,
  getDefaultStyleReviewModuleReadme,
  getDefaultStyleReviewSkill,
} from '../templates.js';

export async function initProject(projectRoot: string): Promise<void> {
  const root = path.join(projectRoot, '.ken_spec');

  await Promise.all([
    ensureDir(path.join(root, 'rules')),
    ensureDir(path.join(root, 'skills')),
    ensureDir(path.join(root, 'commands')),
    ensureDir(path.join(root, 'modules', 'postmortem', 'templates')),
    ensureDir(path.join(root, 'modules', 'style-review')),
    ensureDir(path.join(root, 'modules', 'commit-prep')),
    ensureDir(path.join(root, 'modules', 'ralph-loop', 'prompts')),
    ensureDir(path.join(root, 'modules', 'ralph-loop', 'rubrics')),
    ensureDir(path.join(root, 'modules', 'ralph-loop', 'references')),
    ensureDir(path.join(root, 'modules', 'ralph-loop', 'templates')),
    ensureDir(path.join(root, 'data', 'postmortem', 'cases')),
    ensureDir(path.join(root, 'data', 'postmortem', 'retrospectives')),
    ensureDir(path.join(root, 'data', 'postmortem', 'derived-skills')),
    ensureDir(path.join(root, 'data', 'ralph-loop', 'runs')),
  ]);

  await Promise.all([
    writeFileIfMissing(path.join(root, 'README.md'), getDefaultReadme()),
    writeFileIfMissing(path.join(root, 'config.yaml'), getDefaultConfigYaml()),
    writeFileIfMissing(path.join(root, 'rules', 'global.md'), getDefaultRule()),
    writeFileIfMissing(path.join(root, 'rules', 'code-style.md'), getDefaultCodeStyleRule()),
    writeFileIfMissing(path.join(root, 'rules', 'process.md'), getDefaultProcessRule()),
    writeFileIfMissing(path.join(root, 'skills', 'project.md'), getDefaultSkill()),
    writeFileIfMissing(path.join(root, 'commands', 'start.md'), getDefaultCommand()),
    writeFileIfMissing(path.join(root, 'modules', 'postmortem', 'README.md'), getDefaultPostmortemModuleReadme()),
    writeFileIfMissing(path.join(root, 'modules', 'postmortem', 'rules.md'), getDefaultPostmortemModuleRules()),
    writeFileIfMissing(path.join(root, 'modules', 'postmortem', 'skill.md'), getDefaultPostmortemModuleSkill()),
    writeFileIfMissing(path.join(root, 'modules', 'postmortem', 'templates', 'case.md'), getDefaultPostmortemCaseTemplate()),
    writeFileIfMissing(path.join(root, 'modules', 'postmortem', 'templates', 'retrospective.md'), getDefaultPostmortemRetrospectiveTemplate()),
    writeFileIfMissing(path.join(root, 'modules', 'postmortem', 'templates', 'index.md'), getDefaultPostmortemIndexTemplate()),
    writeFileIfMissing(path.join(root, 'modules', 'style-review', 'README.md'), getDefaultStyleReviewModuleReadme()),
    writeFileIfMissing(path.join(root, 'modules', 'style-review', 'skill.md'), getDefaultStyleReviewSkill()),
    writeFileIfMissing(path.join(root, 'modules', 'commit-prep', 'README.md'), getDefaultCommitPrepModuleReadme()),
    writeFileIfMissing(path.join(root, 'modules', 'commit-prep', 'skill.md'), getDefaultCommitPrepSkill()),
    // ralph-loop module
    writeFileIfMissing(path.join(root, 'modules', 'ralph-loop', 'README.md'), getDefaultRalphLoopModuleReadme()),
    writeFileIfMissing(path.join(root, 'modules', 'ralph-loop', 'skill.md'), getDefaultRalphLoopSkill()),
    writeFileIfMissing(path.join(root, 'modules', 'ralph-loop', 'prompts', 'generator.md'), getDefaultRalphLoopGeneratorPrompt()),
    writeFileIfMissing(path.join(root, 'modules', 'ralph-loop', 'prompts', 'evaluator.md'), getDefaultRalphLoopEvaluatorPrompt()),
    writeFileIfMissing(path.join(root, 'modules', 'ralph-loop', 'prompts', 'assembler.md'), getDefaultRalphLoopAssemblerPrompt()),
    writeFileIfMissing(path.join(root, 'modules', 'ralph-loop', 'rubrics', 'README.md'), getDefaultRalphLoopRubricsReadme()),
    writeFileIfMissing(path.join(root, 'modules', 'ralph-loop', 'rubrics', 'one-pager.yaml'), getDefaultRalphLoopOnePagerRubric()),
    writeFileIfMissing(path.join(root, 'modules', 'ralph-loop', 'rubrics', 'assembly.yaml'), getDefaultRalphLoopAssemblyRubric()),
    writeFileIfMissing(path.join(root, 'modules', 'ralph-loop', 'references', 'host-profiles.md'), getDefaultRalphLoopHostProfiles()),
    writeFileIfMissing(path.join(root, 'modules', 'ralph-loop', 'references', 'decomposition-heuristics.md'), getDefaultRalphLoopDecomposeHeuristics()),
    writeFileIfMissing(path.join(root, 'modules', 'ralph-loop', 'references', 'iteration-log-schema.md'), getDefaultRalphLoopIterationLogSchema()),
    writeFileIfMissing(path.join(root, 'modules', 'ralph-loop', 'templates', 'task-spec.md'), getDefaultRalphLoopTaskSpecTemplate()),
    writeFileIfMissing(path.join(root, 'modules', 'ralph-loop', 'templates', 'run-dir-readme.md'), getDefaultRalphLoopRunDirReadmeTemplate()),
    // data/ralph-loop placeholder
    writeFileIfMissing(path.join(root, 'data', 'ralph-loop', 'runs', '.gitkeep'), ''),
    writeFileIfMissing(path.join(root, 'data', 'postmortem', 'cases', '.gitkeep'), ''),
    writeFileIfMissing(path.join(root, 'data', 'postmortem', 'retrospectives', '.gitkeep'), ''),
    writeFileIfMissing(path.join(root, 'data', 'postmortem', 'derived-skills', '.gitkeep'), ''),
    writeFileIfMissing(path.join(root, 'data', 'postmortem', 'index.md'), getDefaultPostmortemIndexTemplate()),
  ]);
}
