import type { KenSpecConfig } from './config.js';

export function getDefaultConfig(): KenSpecConfig {
  return {
    injectAgentsMd: true,
    injectClaudeMd: true,
    codex: {
      enabled: true,
    },
    claude: {
      enabled: true,
    },
  };
}

export function getDefaultConfigYaml(): string {
  return [
    'injectAgentsMd: true',
    'injectClaudeMd: true',
    'codex:',
    '  enabled: true',
    'claude:',
    '  enabled: true',
    '',
  ].join('\n');
}

export function getDefaultReadme(): string {
  return [
    '# Ken Spec',
    '',
    'This project uses `.ken_spec/` as the source of truth for AI-facing guidance.',
    '',
    '## Directories',
    '- `rules/`: project-level rules and constraints',
    '- `skills/`: reusable skill content that gets synced to Codex and Claude',
    '- `commands/`: entrypoint prompts and command-like guidance',
    '- `modules/`: built-in Ken Spec modules such as `postmortem`',
    '- `data/`: project-local runtime knowledge generated by Ken Spec modules',
    '',
    'Run `ken-spec sync` after editing this folder to refresh generated files.',
    '',
  ].join('\n');
}

export function getDefaultRule(): string {
  return [
    '# Global Rules',
    '',
    '- Read relevant project files before making changes.',
    '- Keep edits minimal and consistent with the existing codebase.',
    '- Prefer explaining assumptions when context is ambiguous.',
    '',
  ].join('\n');
}

export function getDefaultSkill(): string {
  return [
    '# Project Skill',
    '',
    'Start by reading `.ken_spec/README.md` and any relevant files in `.ken_spec/rules/`.',
    '',
    'Before making meaningful code changes:',
    '- understand the local code context',
    '- follow project rules',
    '- explain assumptions briefly when needed',
    '',
  ].join('\n');
}

export function getDefaultCommand(): string {
  return [
    '# Start',
    '',
    'When beginning work in this repository:',
    '- review `.ken_spec/README.md`',
    '- review `.ken_spec/rules/global.md`',
    '- load the most relevant skill from `.ken_spec/skills/`',
    '',
  ].join('\n');
}

export function getDefaultPostmortemModuleReadme(): string {
  return [
    '# Postmortem Module',
    '',
    'This module captures reusable debugging and delivery lessons inside `.ken_spec/data/postmortem/`.',
    '',
    '## Customize the rules',
    '',
    'Edit `rules.md` in this folder to control postmortem behavior:',
    '- when agents should capture a postmortem',
    '- which fields to record',
    '- where cases / retrospectives / derived skills are stored',
    '- output constraints (e.g., keeping root `AGENTS.md` short)',
    '',
    'The synced skill (`skill.md`) tells agents to read `rules.md` at runtime, so editing `rules.md` takes effect in the next agent session — no `ken-spec sync` needed unless you also change `skill.md` itself.',
    '',
    '## Responsibilities',
    '- provide the `postmortem` skill to Codex and Claude',
    '- keep project-local postmortem templates close to the repo',
    '- encourage concise, validated write-ups instead of dumping raw chat history',
    '',
  ].join('\n');
}

export function getDefaultPostmortemModuleSkill(): string {
  return [
    '# Retrospective Capture Skill',
    '',
    'Help the agent capture reusable lessons after a bug is fixed, a root cause is validated, or a complex workflow has stabilized.',
    '',
    '## Rules',
    '',
    'Before writing or updating any postmortem, read `.ken_spec/modules/postmortem/rules.md` and follow it exactly. That file is the project-specific source of truth for capture triggers, required fields, storage paths, and output constraints.',
    '',
    'If `rules.md` is missing or a section is empty, pause and ask the user instead of guessing.',
    '',
    '## Templates',
    '',
    'Use the templates under `.ken_spec/modules/postmortem/templates/` as starting points for new entries.',
    '',
  ].join('\n');
}

export function getDefaultPostmortemModuleRules(): string {
  return [
    '# Postmortem Rules',
    '',
    'Edit this file to define how postmortems work in this project. The synced agent skill points here at runtime, so your rules take effect without rerunning `ken-spec sync`.',
    '',
    'Each section below is a contract with the agent. Keep bullets concrete — vague rules get ignored.',
    '',
    '## When to capture',
    '',
    '<!-- Describe the conditions that warrant a new postmortem entry. -->',
    '',
    '- after a bug is fixed AND the root cause has been validated',
    '- after a complex workflow stabilizes and the lessons are reusable',
    '- NOT while a diagnosis is still speculative',
    '',
    '## What to record',
    '',
    '<!-- List the fields every entry must include. Remove or add as needed. -->',
    '',
    '- symptom observed by the user or agent',
    '- false starts that mattered diagnostically',
    '- validated root cause',
    '- how the root cause was verified',
    '- final fix',
    '- 1-2 transferable lessons',
    '',
    '## Where to store',
    '',
    '<!-- Paths are relative to the project root. Change them if you want a different layout. -->',
    '',
    '- cases: `.ken_spec/data/postmortem/cases/`',
    '- retrospectives: `.ken_spec/data/postmortem/retrospectives/`',
    '- derived skills: `.ken_spec/data/postmortem/derived-skills/`',
    '- index: `.ken_spec/data/postmortem/index.md`',
    '',
    '## Output rules',
    '',
    '<!-- Constraints on how the agent writes things down. -->',
    '',
    '- keep `AGENTS.md` and `CLAUDE.md` light; they should contain pointers or short indexes, not full postmortems',
    '- prefer updating an existing relevant note over creating a duplicate',
    '- cross-link related cases when useful',
    '',
  ].join('\n');
}

export function getDefaultPostmortemCaseTemplate(): string {
  return [
    '# Case Title',
    '',
    '**Date**: YYYY-MM-DD',
    '**Domain**: tooling | build | runtime | workflow | other',
    '',
    '## Symptom',
    '- What the user or agent observed',
    '',
    '## False Starts',
    '- Attempts that mattered diagnostically',
    '',
    '## Root Cause',
    '- The validated underlying cause',
    '',
    '## Verification',
    '- How the root cause was confirmed',
    '',
    '## Resolution',
    '- The final fix',
    '',
    '## Transferable Lessons',
    '- Lesson 1',
    '',
  ].join('\n');
}

export function getDefaultPostmortemRetrospectiveTemplate(): string {
  return [
    '# Retrospective Title',
    '',
    '**Date**: YYYY-MM-DD',
    '**Scope**: feature | debugging | release | migration',
    '',
    '## What Happened',
    '- Short summary',
    '',
    '## What Worked',
    '- Tactics worth repeating',
    '',
    '## What Changed My Mind',
    '- Important corrections to assumptions',
    '',
    '## Process Improvements',
    '- Future workflow improvements',
    '',
  ].join('\n');
}

export function getDefaultPostmortemIndexTemplate(): string {
  return [
    '# Postmortem Index',
    '',
    'Use this folder to store validated, reusable lessons.',
    '',
    '## Pointers',
    '- `cases/`: root cause write-ups',
    '- `retrospectives/`: broader project or delivery retrospectives',
    '- `derived-skills/`: stable procedures extracted from repeated lessons',
    '',
  ].join('\n');
}

export function getDefaultCodeStyleRule(): string {
  return [
    '# Code Style Rules',
    '',
    'Edit this file to define code-style rules for this project. Agents read it before writing or modifying code.',
    '',
    'Each section below is a contract with the agent. Keep bullets concrete — vague rules get ignored.',
    '',
    '## Naming',
    '',
    '<!-- Identifier casing, abbreviation policy, file-naming rules. -->',
    '',
    '- example: use `camelCase` for variables and functions',
    '',
    '## Formatting',
    '',
    '<!-- Indentation, line length, quote style, trailing commas, etc. -->',
    '',
    '- example: 2-space indent, max line length 100',
    '',
    '## Type safety',
    '',
    '<!-- When to use explicit types, nullability, generics, narrowing. -->',
    '',
    '- example: no `any` in production code; prefer `unknown` + narrowing',
    '',
    '## Comments',
    '',
    '<!-- When comments are required, banned, or must follow a template. -->',
    '',
    '- example: document the WHY, not the WHAT',
    '',
    '## Imports',
    '',
    '<!-- Ordering, grouping, path aliases, side-effect imports. -->',
    '',
    '- example: node builtins → third-party → local, separated by blank lines',
    '',
    '## Errors',
    '',
    '<!-- How errors are thrown, wrapped, logged, and surfaced. -->',
    '',
    '- example: never swallow errors silently; attach context when rethrowing',
    '',
  ].join('\n');
}

export function getDefaultProcessRule(): string {
  return [
    '# Process Rules',
    '',
    'Edit this file to define process rules for this project. Agents read it before preparing a commit, branch, or PR.',
    '',
    'Each section below is a contract with the agent. Keep bullets concrete — vague rules get ignored.',
    '',
    '## Commit messages',
    '',
    '<!-- Format, subject length, body requirements, footer/trailers. -->',
    '',
    '- example: Conventional Commits (`type(scope): subject`), subject ≤ 72 chars',
    '',
    '## Branches',
    '',
    '<!-- Naming convention, base branch, lifetime. -->',
    '',
    '- example: `feat/<short-slug>`, branched from `main`',
    '',
    '## Pull requests & code review',
    '',
    '<!-- Required reviewers, description template, labels. -->',
    '',
    '- example: PR description must list Summary, Testing, Risks',
    '',
    '## Testing requirements',
    '',
    '<!-- What must be tested before a PR is opened. -->',
    '',
    '- example: run full test suite locally; new code requires a unit test',
    '',
    '## Release',
    '',
    '<!-- Tagging, changelog, deployment steps. -->',
    '',
    '- example: bump version in `package.json`; tag `vX.Y.Z`; publish via CI',
    '',
  ].join('\n');
}

export function getDefaultStyleReviewModuleReadme(): string {
  return [
    '# Style Review Module',
    '',
    'Provides the `style-review` skill to Codex and Claude.',
    '',
    'Rules live in `.ken_spec/rules/code-style.md` — edit that file to tune what counts as a violation. The skill reads it at runtime, so changes take effect without `ken-spec sync`.',
    '',
  ].join('\n');
}

export function getDefaultStyleReviewSkill(): string {
  return [
    '# Code Style Review Skill',
    '',
    'Use this when the user asks to review code for style, consistency, or pre-commit cleanup.',
    '',
    '## How',
    '',
    '1. Read `.ken_spec/rules/code-style.md` — that file is the source of truth.',
    '2. For each file in scope, walk through the rule sections (Naming, Formatting, Type safety, Comments, Imports, Errors).',
    '3. Report violations with `file:line` pointers and suggested fixes.',
    "4. Don't auto-fix unless the user asks.",
    '',
    'If `rules/code-style.md` is missing or a section is empty, pause and ask.',
    '',
  ].join('\n');
}

export function getDefaultCommitPrepModuleReadme(): string {
  return [
    '# Commit Prep Module',
    '',
    'Provides the `commit-prep` skill to Codex and Claude.',
    '',
    'Rules live in `.ken_spec/rules/process.md` — edit that file to tune commit/branch/PR expectations. The skill reads it at runtime, so changes take effect without `ken-spec sync`.',
    '',
  ].join('\n');
}

export function getDefaultCommitPrepSkill(): string {
  return [
    '# Commit Preparation Skill',
    '',
    'Use this when the user asks to prepare a commit, branch name, or PR.',
    '',
    '## How',
    '',
    '1. Read `.ken_spec/rules/process.md` — that file is the source of truth.',
    '2. Walk the checklist: commit message format, branch naming, required tests, PR requirements.',
    '3. Report blockers; stop and ask before committing if anything is unclear.',
    '4. Never skip git hooks or bypass checks unless the user explicitly confirms.',
    '',
    'If `rules/process.md` is missing or a section is empty, pause and ask.',
    '',
  ].join('\n');
}
